// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCwqRn_zL3-LEOsSIJVHvWPbSLyrSG25g',
    appId: '1:973814638259:android:59af568517129cc45a32c6',
    messagingSenderId: '973814638259',
    projectId: 'sys-db-4f81e',
    storageBucket: 'sys-db-4f81e.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEr35dCVE0dFSuky5v7Za_UFqXFxw5nJw',
    appId: '1:973814638259:web:757bc91af2d2a07d5a32c6',
    messagingSenderId: '973814638259',
    projectId: 'sys-db-4f81e',
    authDomain: 'sys-db-4f81e.firebaseapp.com',
    storageBucket: 'sys-db-4f81e.appspot.com',
    measurementId: 'G-G7PW9PFKSD',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEr35dCVE0dFSuky5v7Za_UFqXFxw5nJw',
    appId: '1:973814638259:web:3487925399f811bf5a32c6',
    messagingSenderId: '973814638259',
    projectId: 'sys-db-4f81e',
    authDomain: 'sys-db-4f81e.firebaseapp.com',
    storageBucket: 'sys-db-4f81e.appspot.com',
    measurementId: 'G-QZ1FTC2KYR',
  );

}